services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - ADMIN_CRED=${ADMIN_CRED}
      - CLIENT_CRED=${CLIENT_CRED}

  frontend:
    build:
      context: .
      dockerfile: streamlit_app/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - ADMIN_CRED=${ADMIN_CRED}
      - CLIENT_CRED=${CLIENT_CRED}
