name: Test Artifact
on:
  workflow_dispatch:

jobs:
  artifact-test:
    runs-on: ubuntu-latest
    steps:
      - name: Criar ficheiro teste
        run: echo "hello" > hello.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello
          path: hello.txt
