
name: CI Pipeline

on:
  push:
    branches: [main, "feature/*"]
  pull_request:
    branches: [main, "feature/*"]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          pip install pytest
          pytest tests/

      - name: Run Bandit (SAST)
        continue-on-error: true
        run: |
          pip install bandit
          bandit -r app/
          bandit -r streamlit_app/

      - name: Run pip-audit (SCA)
        continue-on-error: true
        run: |
          pip install pip-audit
          pip-audit

  deploy-staging:
    name: Deploy staging via Docker Compose
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - uses: actions/checkout@v3

      - name: Start services
        run: docker compose up -d --build

  dast-test:
    name: DAST - OWASP ZAP on FastAPI
    runs-on: ubuntu-latest
    needs: deploy-staging

    steps:
      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:8000'
