name: CI Pipeline

on:
  push:
    branches: [main, 'feature/*']
  pull_request:
    branches: [main, 'feature/*']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pip install pytest
        pytest tests/

    - name: Run Bandit for static security analysis (SAST)
      run: |
        pip install bandit
        bandit -r app/

    - name: Run pip-audit for dependency vulnerability scanning (SCA)
      continue-on-error: true
      run: |
        pip install pip-audit
        pip-audit -o audit-results.json

    - name: Upload pip-audit report
      uses: actions/upload-artifact@v3
      with:
        name: pip-audit-report
        path: audit-results.json
