
name: CI Pipeline

on:
  push:
    branches: [main, "feature/*"]
  pull_request:
    branches: [main, "feature/*"]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          pip install pytest
          pytest tests/

      - name: Run Bandit (SAST)
        continue-on-error: true
        run: |
          pip install bandit
          bandit -r app/
          bandit -r streamlit_app/

      - name: Run pip-audit (SCA)
        continue-on-error: true
        run: |
          pip install pip-audit
          pip-audit

  integration-test:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker-compose up -d --build
          sleep 15

      - name: Run DAST tests (update for your API)
        run: |
          pip install requests
          # Exemplo: python security_tests/dast_tests.py
          # Adapta os testes para usarem a tua API, não só Firebase!

      - name: Tear down services
        if: always()
        run: docker-compose down